---
apiVersion: v1
kind: Service
metadata:
  name: soju-external
  namespace: soju
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.alias }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  type: ExternalName
  externalName: {{ .Values.cname }}
