---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-dir
  namespace: arch-repo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
