---
apiVersion: v1
kind: Service
metadata:
  name: arch-repo
  namespace: arch-repo
  labels:
    app: arch-repo
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: arch-repo
