---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: flux
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.4.1
  values:
    git:
      url: git@github.com:shanedabes/paddlepond.git
      path: kube
    image:
      repository: raspbernetes/flux
      tag: 1.20.2
    memcached:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
        namespace: flux
        interval: 30s
        scrapeTimeout: 10s
