---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-ssd
  namespace: nfs-server
spec:
  ports:
    - name: nfs
      port: 42049
      targetPort: 2049
  selector:
    role: nfs-server-ssd
  type: LoadBalancer
