---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-pv
spec:
  capacity:
    storage: 200Gi
  storageClassName: nfs-server
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/storage
  claimRef:
    namespace: nfs-server
    name: data-nfs-server-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-nfs-server-pvc
  namespace: nfs-server
spec:
  storageClassName: nfs-server
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteOnce
