---
apiVersion: v1
kind: Service
metadata:
  name: sftp-server
  namespace: nfs-server
spec:
  ports:
    - name: sftp
      port: 2222
      targetPort: 22
  selector:
    role: sftp-server
  type: LoadBalancer
