---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-2
  namespace: nfs-server
spec:
  ports:
    - name: nfs
      port: 32049
      targetPort: 2049
  selector:
    role: nfs-server-2
  type: LoadBalancer
