---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: soju-cert
  namespace: soju
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: soju
  helmVersion: v3
  chart:
    git: git@github.com:shanedabes/paddlepond
    ref: master
    path: charts/cert
  valuesFrom:
    - secretKeyRef:
        name: soju-cfg
        namespace: soju
        key: cert-values
