apiVersion: v1
kind: Service
metadata:
  name: soju
  namespace: soju
  labels:
    app: soju
spec:
  type: LoadBalancer
  ports:
    - port: 6667
      targetPort: 6667
      protocol: TCP
  selector:
    app: soju
