apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  releaseName: traefik
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: 7.0.0
  values:
    image:
      name: traefik
      tag: 2.2.0
    additionalArguments:
      - "--providers.kubernetesingress"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
    deployment:
      enabled: true
    ports:
      metrics:
        port: 8082
        exposedPort: 8082
        expose: true
