---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  endpoints:
    - interval: 4m
      path: /metrics
      port: metrics
      scrapeTimeout: 90s
  selector:
    matchLabels:
      app: traefik
