apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secrets
  namespace: external-dns
spec:
  encryptedData:
    values.yml: AgBfQsuvwVCt/cQaVIxCpjB2Lm7lmqwIH5C3iysygfpMkZFqnYrttmrzx9I19Ri8mwlNhSfylt3N9yTr8ucBK14a8MN1UFc8geyx5o2Fnxwf3kLcbm362zCp2phxZ+uLzYZgT8po9T+4EjD7RIRXMdn+lhO/rjebJBa6sCZg3FCgxMLyKhx6g4bo6gW/pAo3uZKw+/GTKTj6CvED1eXTPLLvGzo4e7jEmGsX3aEmF6kwGVwXLMLx4ewIgzNGoPwS+lD608UQYgD1liMDvpz+Rqobv/evZVt0OY6ZD06eGFw62JGJKcQhqpW8aaNr/3XihUnzgdra8hOIeSe1G+jpUGv/1tijQAylO4y3H5uPOAZxyspB0UVoNVijVo2037HAQSlkD+4NV/niH2VrsNoGxomcg+t+GmZkl+2A3PSul9Ik0rqIHqHOJhvaal72WEJEq5MLGO/LczR95nj/17PfJ8+XwRNKCY6Z9SP980mL+Ssg9DHq6mB6fYnC5bLPw4cdY5g3Sa1/TnlGIZj1/y3fay3ngF0N//mcSk1azSJRh5zFCKdOKUrThQdGU/Y84Ks+V0bZY44Sn4z4J77VSAm2s03A1KIsl1G1nyVpAaAuqQ0MjAXyIAvPGYFlBALZBrKELD5jrD25XG973+Dn79ohzJmZ0Zo4pxhDrv98u7b0ZFCbkaa64FqFcO/6yAeVJ8A4e+Q6I2HcMhR69Zo7sPTdrMtd+vmSg7herNgCqD2cUEeS/tLV3l8TFgp3sVrIiacG7ptsrtY9PTZhrY03icT7eP0XTcPixSUqCJdgKZ/8ns9XJpvpEEet7Y28hiheSoWn
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secrets
      namespace: external-dns

