---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: external-dns
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: 3.3.0
  values:
    provider: cloudflare
    cloudflare:
      proxied: true
    createSecret: true
    crd:
      create: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    nodeSelector:
      kubernetes.io/arch: "amd64"
  valuesFrom:
    - secretKeyRef:
        name: external-dns-secrets
        namespace: external-dns
        key: values.yml
