apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgCyGx8u+ZFyLNWTzE6ppVOxlNVg+v+0MqWuNDiZY8PbWrcl7FEC5R2ZKd0NDz4N/Jqcd9EbUGPyam1SBdU+pTXK3SReR9VhmJfLzIH45STU/9V+b0C2tK5DCadwD8vM0JkQkGmqZry90141wus6veJFCQmbKwQ1G+aik33pHKX1MkfaNSAPAbm+u7onBaG4ylmoQKn0vSzc44jWxKU1rDPB2voUys0KYXSKV8jRNqS9qUSRrMQGHlF+HdU7WPivtn9NU9fyFBGickjaHSkFd1fxoIycu3G6kCLDhc14C0gzw46YbYfcd3HNpXknMzYA/vyC+CZHmwrcj21dE9Vkw2iEcJxYPPaxuELRpM3ErqxoS2h0Su0n6aCy/7q8EznVnpa/yqJAV0XlkaBUX8oRowZ4jDXSYBqfLT8vsIW5RsHd/5QsYwq2h6n3t3ez2q0H6tjuJzVHbRKI6rb/4pLZASzYvPagX2J5E0R5Oljf2tWUws5/zW3W3O0BgMyBCuxHT7VQnGa69pUZQ5M9o+j6IzHzG5QcmE1AyPh9swUyA304EijXCoLArJByIXV/hO1lAA6LDo1UdzIyw9aVKFLq1r810gxQ8FXEQbo+ZO8WFhVZK16HqzakzOq4q23Hmt5yDb21EuWcvcvSRO+OhskP7mImMTA5ThpikUARSXwQ0eCrjgNjLpgdabj/W6zjrHbqN55C3aBL9pPeYkJ+aeySgHMizp/tAMoVvpN8OskDkRjM3RFSk4JnYXuSoWpo8khPXa49HhhKYjtjsvZVvUCeVOU850u0fwPB/6HFyTAp3LuvJc4=
  template:
    metadata:
      creationTimestamp: null
      name: plex-secrets
      namespace: media

