apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgArD8zbeD7OEKHmLOV06XV35YwdCGYI6wWzEmj1X4UGavuqPlfg6O07lH4hK9dZpQCtTOmneVJD8pCdl4juxfmZEB57nPVFjUXRmktK9S6EJVZMiRxIrrFG4kdObNzQ1OX/pEHHWD+auzJCKzpUY75HrfFzcIgsuMtH4Zm8UuMG1O6wesKM4SlzjsrzgrKdQE0BaLQdS8KoOtBknFvtPQOvsx9HVdRBWmKXvYtjuNC3loO3MJ5P7BZOFuDYvnaolrLNAoITRr8hQHyDnY5TkaMb1AfQork3SfTf+4dD4JUX9W6H7+VHDN8J3bEv2xx1FOJlcYqhoS6D/6r4la/VDVgm9KNSWqkhzsdZy1Rw0ACJjraXYqm2k9MhsI+M2X3LaQZOrJkyE8TAHNJf67Jz0yswcSdJOI4M5nOZGZzUNl0YwUQg+pIQcSA4MZ4vfXkMr6iVEBh1777ZnqYvwS7yWUWh0Uq+zfJtQ0R8OzWd7Afq1gh+eIn3lXHUatj2sdkf4Wlkj3UqcXfbe/bZi5KJqKmrg+HhIfWWBQbSg32IIy+cK0UJHnxugQymuN9NmkAUa+y4f1LMQDn5ORuxcoPE/29Q4cxr1iXc4z/aG+VZ9omr+IHEwXq3saMsNLp3A/Un4Fe33WLXGpC9KAJ45PMJ7EYdTyunSiBgsTMfQ1SxihZK5eMzyYFBRxq46TX84qDzchOASVuv6/ImDIigx+QWlzHkfPhI8fr8BmXPiBkFNLILDpnAbFAAVMFdEw7hP4M3fBfLSlfoyJ2ZMw8rSrsFsf2Ceckh+pPdQc/mrPYEis91gxOFsevmLHXl7nKoFMb2U77h9XozJrC+BachOz77/pIATvC9uFnhic1shIB8oUam/5hVBVp0JXf9Aqsisfh6w4h79t0FX9bTKTx+qs/9d+Hbif2LC3bnKLv6JZQuFjBv8PSBia01lQWPfufqpGnRQcnu7URTx4OghvuA2sGmOvkXtgd/b5JMPXFlkxIo6DYJ
  template:
    metadata:
      creationTimestamp: null
      name: plex-secrets
      namespace: media

