apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgAv+hBij/IQrHFTBr8oYr59dGl6wIBAow7/napqDzxIIatClg2LGn6Zslu05RcaWXPwZEIXybPPe14qMeB31yTGhJpVi+X5B/pTFe2TWvk6glSgYRzGw/A3u594HsBTDTX5N/Drvygzgzb4mzTbvUGzSuP2GgEeuzvHzMuROWcWeUZBzyuwpQVm2dFLz4l9VHdAwBz3P1VNjx2OlctvIUTyFYuKHr4ZCY1jBaHIGFnk/l58/ebYmoQwD1CUD6m1Wha8p+SwE/liibHiBdxzBXp4OZHhWc2bzaP7NabB8g9wdnH9EyQnPcdpuXQDIdPRJdcfVRf6avreafhLmW8GJrHFIB8jXkfS4DLV72qgggivpOK+sWvA8LsJbOOtVu63UqruawbUPoNq0F8shBeHKr4xaq7268aSro1+nvC1ONj3HkvMiz76948NG4SGlzIL84kwcgn4PSQvsgfRZnlSPdptb+V7FAPEn8NMvgmwB88jRWJsXMCylNF5v8ZPk1ddloXmzid6m/HAMP15c0++sJDb+xEU+254zOcY92vmX2SPoKZA4bVbKd0g2Sems/rINlOIvovz+7UrOW1cfriwzOY6+Vz/LqfjExncXILYsir92nylbcxPTHkdNAYQNFjixuQdlE7dNzQfuNod7A5i8KeuWV7CHqkuoNjcpqefWBRi4vhYrbaO0a9lmDl+d2rHxuUFG4LckbHGuQoxMSSp2LkiT+ooG39nzFxRA28D2QhNOASPEhw46RQMFSy6LiTQggUUQAnmjQaIrbBKfqj6fPrn+Jo3GJQcGYY0kippcUczKjw=
  template:
    metadata:
      creationTimestamp: null
      name: plex-secrets
      namespace: media
