apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgBCpHIKkxbMtRqwgO0KcipRBqL/ygrWwjnspZlWXecS10AK8CYTWFiT01W0tk7MxzzMFyMWiF+vWQuLBvlKb2JgAnhvM7lp59k/PGdtpWSFih7zSXRKyunzB91gzntLwKM2AHfY9r0xhowMKv/rKgh9ss/FQuyYuYCfMOtDhpkNBBZu5DZzAEhwNCZ33k34bDXcSNGgqtdwMSnKJ9esjMybjGnZJF3RJnA/gS+emyRqkBAu7TL8DiDio7xINTffQzWAaSEpc/zGwU1er1odSHltrg/cm1eTBsfXo/F6+mqkGc25vJ7pRtDNBRcd2NJQwglcK583XOycuJgTIVu+P38O2fKCQezoaZOiLy+aLEUlLfCD9Qu16KubeycOX1ONK2V1IbX4ke7Zat0d3PfC0wvraiFTzv+D9u5TjYOjAaHFXx+iOaqJQQg2b48Ad+9vKQvlDVa8blpzz8GrTP1+MX51zlyOkHjvEEbCWsssOoaMBsPLL5aE1UuA0wMSFrI5rFbKn1TwYbjfliWlU2h1ItS4BRVu5ql0X/DHAA2MjnZdbxJfvR3upOgAWED3G/cxq6vscwstZ1DwJInXMJEVaI5PyIdtVoMrVSBDd6S6h7tgka5AE+YCrYyntmf72w8wYWBFQ24dBh2+cQZqU2j6ozA7pPFpIbJFpxJIc4Hq26dh0c8QUwtqo6XqPU5OygL4RZhbbPGpORBGCMgKFlJNLwhHvnZZnoHj2vt3NJohhmhtZrsBDfVo8JeFzQ==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-secrets
      namespace: media

