apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgB/XXmJDrPIaLZgx0/x+yABIRUTSZcahC/XqaVrOMnBg2fjxWXMnJODP2X8z0IUQofGPG2MacRLLEq8UsieOkVEKI+JAnr4uAChvAzdVdqO27mqPi4ZV2ht86zKn3dczPf36v7/sFgJS1A6wa9vfqifeVh/SjNVJ9OwDsPfTakHRnLUMogyqpyN0DbfS1SoGxgXNUbyhaLDgK0XLRXYpoKalPHNRbgrTsfHIg7Xq6EMLq0mGyjsPmKamCbq03exyJzVUCSIchr+CZ0nOYSiVEXaMn36sjSqsO4q7VRj+8IxIjNkUOaw55zIFNZSfPzmIi56R2maKPmZRF+umMbtXORkgGP4Z+0tGFR8Nwh28TVT5UiC11IAXz88Us3pJQCw/jyXOi7e8B4JYMP52hbK1oVe9C8XYn+hy/TBOlUkmR/rzpm8diasUoSrkEYLGzTzUqClGbXNI0+V4Pwnou1M+HFz4uILnWwNJTfbFtmycrWGe/E7CnLxxGHHvBILuMCu9Xhd/SyQVJrJY6i/fzWe4pJzwgEkwFE9B3VtAWrSVZcFrFhZjdK95ChYvLBmYB1CHOlhaVSXcm3rMjaEVXJRAZqTTXEVfqqoprx0sd/HaKb6ANjQNBblr1UoJ7v/TBboimmhfdSQ62k9pDfu5KaXDQWyWbf3pqEC78IudSMYJs8tzS5MyqR/h8PgUFg1iEBiw2GW3MkctsqB8CSYLvmqqLqFQSnomYY/HwxqAzP8XmqqQvMXHRztJMZoRHrkrzECH50iK6ggyEasqb+FjHYfeVOnb30m0v3JcSbthzuiLot+rM5n8WRrPrtlT2jTM5g5sA==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-secrets
      namespace: media

