apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgCj8mh8z+l5ZAoq2iyjSsmZKnMfiveoZ/9nEZtt5Aj16wxay1ka+9YNHPW+UBlTPe+ZqFBMztWByMbyKOV9u2Jjv2f3NMzXhVFjr2e0LpgjPExF2eSHOqnu+RE2HwltfzOvDxZa1RMHXsJ7NiLuFHZTiHr1pZNl5efW/e1nPQO0Lg6Oxaf+AzNcKCQyvM7eY0yZ8NHjIEJSng3O9bjcY161iCbJ705zIrpujP+CDx/O7DjrimN2KEw3dzBstIZklpqjvX/UR5uLs3u7J0ya/YPrW529NejiRTfhSW/5UQlv6t8i1KOaPmZrvrT+UVHhWEPKnSAlba2CbyGc1mppv0bmhsUN5L0RdOJ/oIMhoAUPqj4slOozhrrA+lbW5SjgO6zyTrmfgpNxr9RLkgVh6BSUPHYA6VSvZkV2IJn97FtjyTSvdm2mvws0wRHsc0SWnF9vc0Fa7ZnKtwu4jfdiYmQ6+HEsOMHOILKynYK6rIqDeUkVXYtC65dVdkg/IXK83Gr8vkxgL4oRXg8FSxn1QU7Jksv31rkx76GYpHuYrbEZylP8GoTOmksiX5Eoo91XifiGVDgpk/x+gPG4Ijm4rwFpJ02cnkG8Yck6LdD4txmO9pHsyvzkbRh8nr6vTqhAgVK4LcnMXdlFy75ydeO9SsxPQ/CH/1rzp5g09xnz8LEblubx74c9/73xpJWnDdCiugBnnOz3whJtv36XGVAudb5H8lexMle6JNHqUL/aLKKwbw3TCv4haQ0OEQ4OJvulZ55bphpWiNM8pPH8LkX2RZ1VmEQZ4+An7WTZvHcwT2G0a8i84d9PigK6L+rB+4PzaRm8x4fFAOBkUY8K+3ZMDRaBPB4fvvssQAT8mIrrkvnckYYLHVgXr9T3S2Fzoa83OWft8WQYAsxtM3Z//M4QnUg+dNDofHrcVPiFGYDrPvVucei42QRNyu0EBhngH50hQF59SV4cG/AN27HIY9yeNnJFarVIwz0CeJJhYMnf8ZWvpYcXyoSMrHwcrULmkp0pUFHSNIcHWw==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-secrets
      namespace: media

