apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rm-cronjob-secrets
  namespace: media
spec:
  encryptedData:
    RMS_PASSWORD: AgA9LFnXKnoV3ylPBS4uhXuAFTbZekEni3aCxE/cIzKbHQg1BErFeN2879qguWGXcTWIdYTBGN13ipAySRcs6lP1w3THgGkdTNqnGyNfb3f4/pMuNgY9Di8NgHLg2nJdMXdGzzlcnIpX8gZDdrhyLzfVDZdu4DosFhOpEKxcSGw5fdsiTj11Ln0R/6vN5jgG74T+axnasWqYQee3vCBvO7DbwO0MogYIa1PIj4IOKN2eqtcv6swsSc1YTDXYnPf+PjK+ynx+hyHBTGJHJRqe/FnQAHBG6HMA3mBzdFvFucXawIeVephrjpV90H29TV3nlvd8qTgstC6Do1a5ZM77kqUf0FmpuYl/XA+Dvyh5YGqiUOXTCk28j4eV0sbrE0MQrtc/mpJxi6EzDI/2RAHBiC73ss9pAQ/829hd1XjQu1Jh0MbvrWPv2Mg2BbBfxGevg3g8wSZ9xPhHwTuYxrecbQgkeSdKAPSpNU2fdsISiPSrqCIM8fxUM3Wbt5sy774WPWlAdf4aZCIxNDxjqpZJwyyXd/hSE1hH+Pjxi+M7fzR3w5CZ4UeGjQHwBr9oY2Y6Xl2Gx3nacK068YQuDk4uT+5FQl+htAEajsJT/GoTWFfXB4VPT3qdkgapc9PaqUpZBvaHE69jGj//Oeox8Um8GdeKgp8G2q1v12FnxVauQHShJmWJQAp0joyxfFcZfHy+RmMl89YubGTJCQ==
    RMS_USER: AgCsa+33RKHReSRHihVXHgx2306WMgeuHAA0duVcW1C5hyu6tbj4E7zKokUA6fdTjW1rLaDWIHYLlYXY7YCp21lSZYBSbhxhDrcNzsgK4YpcUSe2LZEPfeTcZFlk7u3CHXWynb0BmVNY/HVdGGOoUyN0eYwb93iIe1pibQjalOAjNxS7lJaQ/OU2eXxP/irEGzEe9NiuZ/Q01+EANjec7VbeaFjINZgJ5lFnp97yD9vxr2lpXwONV8TqaUu4ykjjQEo5MO2DHgthSbrcbfRRRF/a7ROgsBvNklOLxgyippLWPL1Ww7RhNQdUClVsHLYlcKwu113aa9wyUXh+7lE9Qf7OB/g6JSThImqePNEAYUAfvNQr11RMOdUtt2fXNAoctqk/r56cXfJxRj6Jbj5vQdI7DS90Y4MkxsOmzady4RBwRRdJvnurdzJ72gEp5XLAG5DX/PnS/Kh8fJRkYCOn11Qmg0gxsX85ABMzrnCgduFqZTn/J2L2ebuYzPShAReBsqIaxRFzVq+fTC75KszSfyPmHDhBTDNrQD3VOZPqbNxJvnBZ9+RUiOu6bqte/BVtwV/WB0s3JGYm1RV9CB7oBs1Hea1FyhcNcvFh/KeYVKmeuZx+hwCu8cPtNldsQBPOm0gdrd0ASbN8tsXPlmGevI8FYyAa3aM/HVlbf0vOQynXNDZmXck6tHte0w2IBUnJq8omMjgXNA==
  template:
    metadata:
      creationTimestamp: null
      name: rm-cronjob-secrets
      namespace: media

