apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgBFqjgEZNhqnkqZxDWPazV+rypeEH6lpLjC6se0y4MEv+bF8j5bQFUT1K0iNMBpcOBimb+TAyQhLRc6I+NQrgh+g8VYQsYUotykb3Qj2cvC9T3CqN5HD/hyjx1rVrKkPO36FxBBJBbRp7kc5Tt88cu6JVJzWHl2YoS3yMHKbJmSCd16eFX+TrjKahm2hHUJm9EgezqZqO0Zcpt0mQNmPYR2zxnx+wcHXDnfs/G1D4XoH2PfRHuwi+ikl/VpzJb+2i7AbknCXizXZqxVTvrloh2pDM4MyvVusN0vwlO86JKSD6RjWZ1ke5BUWaOVUX8CYS5JeqrzwXiDKfQ0xqpJSBRrZUJTadaWGbPlryRhIu2UoXXcbgTkihiKGPfw/ETz5V2Q576qixrBij9i/3kTiOni/h/LsDftyqIPm9wbed8ZvARkfVabek/GXNS3FTE4vqH3uLUZDmn7exyHlSPbs3NlQ7eXGBmiM9Hn3chP9jGp5JpvRw3E1y4lExUgLMVXxnRIJ14OWHLxDKkYqUiLYquJGeS0bea2GIb5iQleBQsGcC0HuuNXTkPx8oAs0oUgLtd0M6dQkQAGMXWMiCusq5MjY38AyEPDDvThMPZlyIPTTCq0UJg1pvz+XDWh+RvFuuKk8JurYgSclPytxyVN+WUNpQs9H2fUNtJSbXDtIfi9CFoRazQ4BDMo3Cnon5JZG4Ay72Xl+aA5ZDwoue7ubAEFiXSUfwKninMSdNxO15IcR75sxOCAybnQQ5cl0pLv0hJbolndpRce7TDGltE+YmWKisWYgKW2HUZut3BgC4aklCvpMlkuS175D1TK5dQWRw==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-secrets
      namespace: media

