apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgC5txkpBlM245JpqNsnBCEJEyDFPSb7OC9Sqfa0Vwnf2j1Ge6qqDZ9ezwJYuC++3apTymFBbVJWSW9CS8LxKQqxeshHQcDwdMia6GlIEuidHb2pc8F0aCWQAUbo/M7C6y+xIqWk2MkiAB3J/I6F5Gy3JalmI3QcYrpTP6jwQg5iD6VdKZ6WKBWKie1cwfdtvde1JlOCtgYqTvhDhXvbhG31I06jFvG6bitMeUw9TRv5ats++Dxx7co/JVcAmp1XUpLiyGk2ZPhgIx5Gpf8HAEX4ncWqWnqIcJ5YZnptUEP3nsTLHGgIAP5ARvEpOacMjnW+DM/H80kTjGfKR2FfcYuDqQPelkru2TqBnDaNs7sntzI55wPdcrSJN+UENi0dtS0Q57+GIgEvRFz0yNZmCDhd+sg0+SCEWwsskYSDXKJS0WYJvaQuJZUHUoRXjqFDxZmWVzVqYVFCvar5BSYob4KXb84FXwJz8gW21mOCCTjPvIXZJObD+cHxV5OsbIpDD9KBs3wk5r2jF3EN11k+KFVk4ysRAZ35f3PexrvY0u2nNSPMaMLRk91Dm0VysLyr2cNRTQWhXkZ90UB1bDqXbo6rnL5JjNnFidGDJ6MemejcDSctM4a7B0ZuJHxO5CWmABfySe8AuSqFZzM+jHTGb6RS8objmiaXkB0z/gsjXaTFqPFer9nv1RckI8/2ebtMdm2afxsETALhklZD08Jd1zYc+5qc96KZc1kXn9xRKej5wlYlRKdHp6dZbw==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-secrets
      namespace: media

