apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgCZeimJbHrGh0QqDq4dik6ak9UAV7dIY1fLP4TZcfvAow3yQtLLs0gQHDJkApP5a16sfFtN4ohxDNRxjXwHJovR+ew0Ig+4crYqIRubjJjrKz+etxSpflyRp5O0cZVPlfa8UETRAniudY8leGASjK5a4E+XOdmu6Org9SSY7q9d6Q+iueo/92u+5uF2oXAstRrjToz0USa1YjKi+jQA6xYUPsr6heULV8qWvzKhUC/BiwFATEjfVnO8LrpCzyO/O+54y8PKyjpmy44iSwFGOVUq0fMnxY2jJpSYWPBCCXR5AGoIr8ud3ZQxGOdK0N8Ay/Gvdr+NPlCaR0VJO8mtPymaPlY17osnxeWf+dAFrSqt2Yt/ct9xCaPj10Wrky0D/toIL7DGv49ynSC4UwjuSA7BBlw0H4iLf15jsQCQvqfKCnZKqZuUYA6+qF3095Knu4fCiNjam29iQKby0t3ACjrr9+14hOKWTp0wvmehBWaptXhLuSTzZl5nVNjm1akSonC1I4HFeyKmJTX8/LeUDqOO959fV7kGcbvMBTaSa4vrB4bmrRQsV8rXiCOwtzz5jNVoUNAw3O7lVOerCkdwHRAyW5NOx9ly5uuAQZjmdwJcExq49eXkM79ZDKDdCzV3HjpqiSGircNCQr0pq2Jd7ZkzBAQEHN9jLMbzScw3nEb3HXW3wpWuIqRqZTCoYcWnkCNosYh3o3k1AGdG5hEUZ+pRGYmVvJ4EUgz18oidzXKGxqtGPtHg7xq+rTPsgOlPw7wiEqg6e0b/eRItV0+DbSDR5BLNzqXSJs+l4K229Dn00Qlc69Zja4PFnelymSsNag==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-secrets
      namespace: media

