apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgBh2hwCo2yaQLwUnjbNikj/80fFI6qtvFzOqFp1TRKBFcHLxnzGeipcwzT8VndSUqTFgjrEAnIuTUFmyN3cv88Od2mos5H/c/SVxqoNKAiDceakPQGtUdAS20qdVo5wt6RUcIdI1tUjk095w2IPaW5HcPijeoGLkdkwm3Iw1YGEXebQbnJPNfDeRZpzpLo2e8u3S+noL4x/4bowdLQv4C3vFzSn3zZbOD5Khoa23lPbRpyLynC/4flPA7WNoTqZ7KuI2oEHo6K1ws/T0YVr9crzLGXllGQVBBlAsA/8gb7dHYxwYSGqvfnyjfqslBV4WIM8JSp6iRwi3zt4DxVAJCDJvbUEqafDPl84VlrAkIXb5TeovBgY991ocGTukIyhmN1KTILG39TbBJrvqP/C6VNNC98gDtiQ6pbqpMxRoxS6yMTjk1MLqH7vL3TUY2CUwIHu2TCzKIFcLgOIq0EqvBYi8QsW0P2+f+58QwTQJMXjn5WzTGslY1FRXYtrJB30m25x9l2uWT+oAr9jMZ/R5v7444jvyl6WzVRPnyT2bL7zUUDeGG95Hc3eRKUV9HCrRDbDF7l9yPrOLYm+PE57IFT9o5XomE4QpxjNTlx4XPugNRk/R2zD3H52OQu3ujoUKkayBrKWnjWziNWnL7+N3Yb2KVJ4+VUF1QFcHa7tHXXjvb61ka19uamBhVekOPOYbyxCwFcQ3I47mPZZoQ2U2irQSqdJFIOubmC+zBdm86m8NrT/a8gayNOtcA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-secrets
      namespace: media

