apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgA27H6SsaCcA67AjGx20gXJOB39jWeyWiZEmw22u3f2IRlQGO5ckw8YbYnF9dkxLIRuasU3Pn6jxDEC3B5BdkO/5PL/cqw279sMssa2uuRdI5KJslje3jtpDYRp8LNht6aoyYc4ug+CqiWZpmfHGVuYtjyRGtTyCC6hYDC9nvxGijidDrzHHNuKgf24H0P6b3nT8xzE1fUkO5bXc8Kf8lltLJi+GBuvT/94SP8u38uYWHkwCoA0dXU5Q2nu+BLTqrXm/u+OuukUpwoDzwtAne1C4MFn2HLEbPyaOwqvIAmbGUwsYEHXyEcetok+XFHYrzu8Vpjq1bhnDB2h4BO04WBEXfr0ZXHtUXiQgYokBP4PKbvhHfbHfXgoPiMjI8CZIxksWxWFTvcTS0aL0yyVP/TNSzdR+J2FFuQHZcDcsd3ttW6yIex9Bsf/0u8mlR701Ofzj7PrnPH+MGAaUsNYfZdkDxhT6N00ZIt/+lQ3y2TuZ1HX8mex0hwiJBN+JuEDGDhC/ocv8Uy9mtQEe/dCmO8/tF4FzdT4xcKqVlmeY0UQQU4GsWjWHQjelCrxlgH1ILDVtOsrOr/7oYBBYXKbU92r9Cv0tSMj7tAFX64U3swISRCgu9/wljiHJ6nccIeEuVhI09afq0O1WAjaibXLFiDf29msiD2zvsc4M4xVJdK8AXE+qjeshlWoDKsmFoa2SO2+hTabqBtDyfAvDlZxd+2+VmmvYkx5We9MK3MqyITnA/wFyjCerBazOA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-secrets
      namespace: media

