apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgChJc02kGKU7JD+7sidedu5UtmHNB87ZMCordtX4sgtqTCmsetYF133CpINWHB/Xzo9W200bwrArmfTNHDGbFwX606b5XzC9TQobd47FmR7w+EExyIwHVa9vFKYWfGrefceSCcO0kJokIz2NdxxHHKZOwDnB3bM5fUZIeUV1SJv0SJ83k0LJGtYyRttTawktRoigWSg0mQdxNYZ3D1TGtC5RXsXzqdPHw0dAb9YLHcJ0cJAes+ZR5qQofdm2Rm08TwDNY7rXgPDYP7+E45MZB5C7j93CqFIWtqj0HAq7CAP3wqzzVsm/D5VGnENZXrj8/15npoxkSlk1ELofkjb3vhYxMScgeKpyuI0wgtkyGTgGYVbwxVaAdLYBLEY7f/dOq/xpY947F5PUt9DP8EfcHX6ZZr3HUkRiK5QhQm2C+ROvxxeVGt6K37mhPNZ8rgv8mo9KBy+OVxzSfdtPayKI53pTw0nZ2T7Qs75ro+jONWYF2KYCBHziTpb319usKsIhHyBVrNEtA4X+CP9dsbx6TNWJn4ltZ0Ahf2NGTf4ld2WuBDU8OHBuPajGGBHfOXS71tahvLnPq16TomMSysSHMFRsDKhnJ16I+URfWoZT+HG4+FNZGTbq3OfnbkRdlEMW53tM0U49vciFh12Am/Adj7zXYgJVyXtayrulTbyj6A8bTvqF7S2S5nxiybj4XglsfidM8NPJLACOOkJA2mJnCHCHX1ma1jY8OjzR1r1yhRJVDeD/4ymbyvDIetSy35Ec0YBwdJQAH1MdCf5oNbt/JkZjuEBE9qEJL+UUkIkVbY2BNQfNrhARVJNg9ab8MtTMHTsqhwiK4Q3zgKQbwK/Gibx61+lpFPR6gPueN7EqgK7QAWjllfDnY98YpjBzZNgKHVrkgVN0/yyWGSQ6dLEEhzgbI/ZdJ1TqUMwul2Ykg8Qgmgh7H5MBlt3/cTHa2id+qqZVevlR0fO75VeAqBd74BlkySF4U64gfuR9dbPSuPdCp68UG77QpQko9WilMiUWcbc3A==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-secrets
      namespace: media

