apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgA03pQMV6SS28njk+TJ+z45caDR2i+oxQXP/4zGCdTIllHdSY9JY20gq89Wu8WMPy11Aeu2NKIGHxY8YdPotK47E4a+VWSbYlBdBW/YE2ZNN1xtbGbXHZIptnCBV8cQfrt2nbiz/UpJlESfZy4EL2yRX3jpCKAPdOCO7ZcLvKqjqBvXR4WM5oqqG+5CBKZ/vTaTMd3rwAJrhAEZ6wB4ab+OfjK6d/KiBY9ZBYX4FCdI5xvHn7MB0JKMMz+ScO3KSsE30Y3dmp7S1rV5J+V/oB6R57o1C6vK8dlTCRSaGnslN3MxAZxKieZBuJqvFEqUuQB5pixmO/GNQRj+ozaEnkNKlla5STOTJweJyCUS4JVjCKHHINSZrrPhxSQSPKkx+2ZvHVooayCKjgeotSW+7/Y02cQJa0Tgx4Ax3l0F9vlLCV24X2xChW207X4CN2J4gTZm0HU8duMNgs9GTC9w3HGKqMonjOAuWV0DdGTMmjLro/XuZUbq+Yel4bXEJZSKovHfgqv9leex8dU0Eb5/VQtn233Lv6pvqpHZ85pQcnp4qbbsTjyZUnmNDJMKmYm2vLSjOWyh4lJjaHAbuzBrG17RuT6cOCkAJQzLE7qTFT4YrSJK+nAcolJggrg4hTXA/UJ4RWnpypPnSKIlUnjfuvZPajND1u9C5eh4GSQ2F7y76M6VwhDgNghLUMwRN0E8eEjU8GPz9ExzXiW7OkLScD5zPr5uRKRT9I6792tg0uji+3i+5U9fgFlurEeUnE3lh+/jTnBqTQgj3QglhBtry9fMiv2aRvRmSb0/SisXd4LanT03HrIsAGuhuJItB/dmb+S0GrmzK1pgMbFvpwRS2KpnS7VOGdqaDnPmt+pFz1deypMO7jn1rm7ZllILEA/GqYEGFIMEwynrQonrg/L6V7HCaBEO/HR4v/Nx6/ooPJh/pFcLU+oqArmfcO3VFa07BiHz2HT8j8awGaYYhdLx0UGGhEmLgYxkA5pBWpEgQrqUqKKz6YXwdQ25rOa9fqZ8QZk=
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secrets
      namespace: media

