apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: media
spec:
  encryptedData:
    values.yml: AgAyloP88NJs215hnAHHKXS5H6GZI4cp1cHFBR2GomyjCxFcGQUYPIlGvVFJx/vSPJhee6TuSRIele4dAzks89NqmC40z041/xwj7dVeVjwH++oVn9pEVFxPQ9ddFFVUYiMPiaRZ+IGPJY+aojAqAkzlO6WUPViFSSN6xh2MuTYC0ghBaPJYUHOKJBOiQna+C4IxGyvRn6YPHOQu/vHhn52qpYyid1iSGV1aiUWfaqzqVvqRfyPuUxIF2zedg0NImT46TUMRg2IWdSs7LQM9Bq8l+8qNgcV1G+MtUJ4YaVXiQuP8d1AgkjK1slyb9s6avAJesOTYgDQDpy2/lp+lAV4aMpGkpeJigelBy7AmKresA4tvEZXkqpDMuN1ncCtPELX390BAVYxOSQhBcvauB0sai5VuoDv7EQbcs2lP/7n2ZOrTCqAHlCs3k8YeMnniPcl7zwOVN8SwPQzxzzsPkf+4U4a/Dge7C032qEHbyjYdFR3+h/qyBgzpuujqnoTB9gdAMqjdgrBKmCaxpazeIepjTrIA6FDMgs6MhJJ38Fp+OR9BfoZhBTJJB71YC1JmL7wYzGbsUSzLKPJUmqx+boRzt93cPvjgLi6XPjZMKh7zsihU57zKnm7jp+yeDJpdtKzUdEZejR6QK3S8ML0a6ITJzA6T6Als+OHzvI1yAfmbYm9LG4UznS4nRx2qjylCuVQ41GfBm+MVhDTa9BDGzWxSd6WTjkVFyUy6FzoOuNUwZJwqnRxx1JCwYUzMY2xtbhcokezPS3hYd+8olo6MBftpf6y+05sZ+o3tpdola3AfhzH0eXjb9s63Ck3O3X86J7M6ZOCoVlxM0M+Kvnl/ykM5cZu+HRLQe8h4xQMENioz5WE4tzubalo8BrPpx5821MCcJ2sIFTy42IJq0vGCqLzqQlMZxKz6nKgJTyM+1zzsiUvqcv1cJ1XtQEwQaPE91CNn2vN6+qzoesTZlCEEo+CH3H68NmYW2dVQcRS5fRMccf/XP0iHbriZKo3fPv8TltgtOUqth6Chfwif9kw=
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secrets
      namespace: media

