---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: jackett
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: jackett
    version: 2.3.0
  values:
    image:
      repository: linuxserver/jackett
      tag: v0.12.1132-ls37
    timezone: "Europe/London"
    puid: 1000
    pgid: 1000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
      # downloads:
      #   enabled: false
      # extraMounts:
      #   - name: media
      #     claimName: nfs-media-pvc
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valuesFrom:
    - secretKeyRef:
        name: jackett-secrets
        namespace: media
        key: values.yml
