---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbget
    version: 3.1.2
  values:
    image:
      repository: spritsail/nzbget
      tag: "21.0"
      # repository: linuxserver/nzbget
      # tag: v21.1-r2311-ls5
    timezone: "Europe/London"
    puid: 1000
    pgid: 1000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
      downloads:
        enabled: false
      extraMounts:
        - name: media
          claimName: nfs-media-pvc
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valuesFrom:
    - secretKeyRef:
        name: nzbget-secrets
        namespace: media
        key: values.yml
