---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: transmission-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Mi
