---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grocy
  namespace: grocy
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: grocy
  helmVersion: v3
  chart:
    repository: https://k8s-at-home.com/charts/
    name: grocy
    version: 2.0.0
  values:
    image:
      tag: v2.7.1-ls79
    tiemzone: "Europe/London"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
    persistence:
      config:
        enabled: true
        storageClass: local-path
  valuesFrom:
    - secretKeyRef:
        name: grocy-values
        namespace: grocy
        key: values
