apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAI7NmzBq3L+Dl0LBuAdMUNOQhffgwkw+Drv6VG8xrJM0e48JKEHOMiNn+SNyStjPsu+UBvrGItYcOfx/FgtpULxiW0q48pB0vrJFPJE0GoFtrXiF4jjga6RFVebS7UVyXo0UdqWctQmdkl9Ij9ZhV1xpAkegS+D+HU/vpUX+IbI8n/qh+pkc4MAn40r52G1p79C5T+1JzC196nP/n+BJHUroVcGHHsPvhjXu0G8RArtyivtxgF8O3olZVLoLXYAt5kZZZR2GcK2wdVu4QvCq9bGJJYeFzrLM3rzzDs0KV9ZWfwHRbXZzvxfsYZa0t5pDzEJiELmtpT2bxjvEOhY03CfEwy2CpGcM6DV7JwqSIcu4DEss3U0ueWij4h1woR4rxDuKg/LBcqdRa1BoY2EwrJNYx9ck2nYRxuqmy/OtgiI5cwl5wReWYrPZpHHIp9bP3kmibzHQlkYFrONlQvkMvNiD7w4qd8XZ+1KaniEK2imwishHmfHgTCB/jkuPadU/lVxxuAd5wN4pV/ILi7vQOgUYLwFpakO4x1qWYfptiL0gDmguLWh8YJVTHCgetcfsAlJhc/kliG8q/MgvZWSOgnr1hOZ2mLWOivHcoCGEZa7jagUbTzjbhu9U2vXqUbQxQ+8PWsUnkqhLK6h1iMNChrkU0Jmd3nEY2O2NdUe8wM3ql7f3YSyPZfeQfeKT6a4uCISaPsLj6IPAOCfSpWL7Git+PphiiJ7Ocz58j1v2vE+4zxUFc4xH78
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

