---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: cert-manager
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://charts.jetstack.io/
    name: cert-manager
    version: v0.16.1
  values:
    webhook:
      enabled: true
    cainjector:
      replicaCount: 1
      extraArgs:
        - --leader-elect=false
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        namespace: cert-manager
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuserKind: ClusterIssuer
      defaultIssuerGroup: cert-manager.io
