---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  rollback:
    enable: false
  chart:
    git: https://github.com/munnerz/kube-plex
    ref: master
    path: charts/kube-plex
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.19.1.2645-ccb6eb67e
    kubePlex:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      timezone: "Europe/London"
    service:
      type: ClusterIP
      # port: 32400
    persistence:
      transcode:
        enabled: true
        storageClass: "local-path"
      data:
        enabled: true
        claimName: nfs-media-pvc
      config:
        storageClass: "local-path"
        size: 300Gi
        accessMode: "ReadWriteOnce"
    resources:
      limits:
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
  valuesFrom:
    - secretKeyRef:
        name: plex-secrets
        namespace: plex
        key: values.yml
