apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secrets
  namespace: monitoring
spec:
  encryptedData:
    values.yml: AgBQYnqKoW8eW5hkzQfyh4fqV1tKVLoDzlaQt9Zh9/45m3gmipcyGrVeBCzRRWU8TQ+/9FNFxD79kWJirAwEOynLXA5JZTHdphgG36OvfXE230F5+VaeEuyNbV+YltV4ApvEfmjjy9gmgHX4t5jCUtAsT3sPAIxWE4j6dJcA9UsAEPzqt9GIBOB2d2Ezt9N8uY3jzmIRmW7WQL+IGbpXeuKV7mgNFn2iK687JUcHzgf400D4YzoWo65qiww45zZi3VI/1Bsv/N5AqLdvTcXVyWfkxDko5ecQJ41VjhGKYtCneUXTD8PFiw6YEAtR3crBvhwUeXLc3x207JwzET1qiQQ7yJMGn3weS+tmuhfF+RhSAGtTCGkYFGYfO5ZsiUre1KupkRBQeA8Hs+c8+/FtfJV2RULnEoHusgDtEKpJa8M6Q8rfaB+hJg05lfi0O/W+Nnb5fJlcGtzgQggTpNHT12vZFxQKPOmgi82clMvSHvChKk8Hq5qCEowZmPI0Wm+aJsloIK7+b81QNZQZ9mlyRSY9/csMa80b4MsLHF8cWzPKIQj/ufmgUZ4UVDMDBTRsXzHHZQpi/NnFlJP68tFb+5NR1B4h6Cr7yewBzsDEdKoC1/X+7MR3x96v9YeN+Prpli8d22rCGIyC7yMgvuaXGwoAAbJs80TR0HLgM3QwXL/7piIqOwdK+EvVfCIgHDq0Y84yQE4QjlpU1/nvR3HjOiNGzIQLD1h/OA4Hquyf0vPbiVavRhx9CJ1EhAOWPEge/dP8QKiYPzhE241y2xWIhUR+hXemIP3W1FrX8woCacxIf84N3SQpbdVxMkNygw0q/gkN3iL6R9nme/7KKYaK736U/srEK+0mVgPy/2DRKzMn16a6ijdnEEU8CrdHC+B+3M8ll6rBUYCinBstqGaSEzeHL692tvZ3sEMbWeWs880iF62QPIyyTwg7yK5xBAt815nFTiTRDIe3wc57jHIgtairJuwflvl/7RFXIdMN11rRZH2Y8kneGYeFlOJ0g47gA9xIui/Yk0sxGLhEeJ1uVLTdmWQsTvjbPRc++EPNLrlr2i3zXPXK+/Pxzb9FWEy/LEg9q8NjimUMsdv+A2vIlaN8dU7QDpe2yfM2WxHsksNtW+rd3zhuYTLo+VAjR0ERgSgkZkSKCr149cd/NSVkgzQ7pZqjoSgXqq/zGRiiFD2f8t56wrFi9D9k2iL+SfGdHUHGE8i8mta5WE4o6ofSF5GJvzVsC9UUYI4RPdsUlThX306+oAuco/zkVof3yqjhBT1s+aYnH/z+x4O5HiotUYxL8MTk9QLe2YOBq//wPjOa2igBuOCL5RanFb8btWA=
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-secrets
      namespace: monitoring

