apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secrets
  namespace: monitoring
spec:
  encryptedData:
    values.yml: AgAkbcN4lUr7znlfZ+k3m1l/f77lYEfgZ3uks90Zv6e55ud9j2FFM6qP+NCoJm70GGLUk/V1xYTEAkBdPO4eQ8+qdnkt+3f8Fe4XUaWx6P8LbujVjx9OGGOGyU8AIGC051KX9RuK/8JKvxxgPCcLf2RvZOhLktFMdBi5sXcd9TPOAyOI5druKo4JeoGN3tiS4ve7LR9gHvP1LaC//JPdxQqAQjeqrTrWVv5WRYdcktXgflzgcwQL30kPk2V6LbdFqwQFbEkuYNfDkfLpIuhbKmcw4SSpo8/netZFxANWxfQ2md1K5sU+ZoKwNPWYj/xdVfCdoRqoxlmqDGmAkRhDXo5lyC3PuiTBo1aLQCOCpna6BATTwkVJ1MSqMCWRJ0uXEL7hKHb++rprkNoCxJ4sfz/XqZH1kDmiIqoExsLaKSpKvXTFtsaD2DGrhX4Ea/CWKeKT5evVgEfd6vXRG4afYz/tvQ7/hOqZS/3nQYqHugeLNJVMwctLFK+Y7RzNPjifadfXqEeCdEMGgzVs7sq5xph3oioRKUw+M5E1KOH1E9OJy5DNiFsnHe8z4bE63EbTkdSnY7Z18veQOyMeZ+SPuit9iXklcAuQm6ROvCjVblHef4JtnGdLKorPI+8j2pAXsDvjXmPTKdLL91/tAPFf00JTiiarnIcnlrHqwt4hQtj9GBv9url8gQOF2Cj6ytyJZBqZ7EYBhmmS4n2xAiBJLC0p0CVbs0siSUukplRNPe/dH2AjP3nOwguH44TSI4/tPaI2Sk9Y265/7pq1LEDYi3mkkT0SZmsVQNhuQBdNCz3TF7grIEi+jQo5d+ikQl8LJ3PTcA4mRvLwHLxfHNSpSJ/lwpDHnSMaxmoi6C+/NSKbFqjWXC68sWkUZMkzK5tuukaCGvwro3BYWF1tEfVibnHE1yivaHHnS6cw0/48W0ZVQw+V0e5YtWcaZLtMl9+LuyZ/GfSiv/ohGJIjscbiP/A/2Brq2xKgHnujwlCZ6y0=
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-secrets
      namespace: monitoring

