apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secrets
  namespace: monitoring
spec:
  encryptedData:
    values.yml: AgAxvMHKMaEUcOkm/dsocuGRjVwjbZlYTvEEH06pcgp/l/ybOKYXc9p7MPJdYCzPKEWpEZfCwdqYyajENW3cJHWKdcTNzZ4xGmbS2vCwp0f3/bIGAbdSG4Ul+UA0VAhEh7HetWptfVuSDuY+jZFvRItXceDeo30sHo/SBKi/PiLuHZUTvRI0/NBig6I/snWxYNddlSf0WXjXV4h7tzQDppsEY7llM4ILgCPpatd+yND10Uo8OHtRmn0VF/LamwSinywd0Fd/8ykF/J4D4fVw33ISIqDDg1lzmC3UpooAJVolCpphGf16whB+ZX27ZC++1oJJclF9LeGZFg7ij4jQdaaPV7brcJNE4zpnoLt4qsJjD/bL643YcanhS2FaCwItnZ5owL+D9YNaUWrj+zRoW1lvYtGbSNh6FUqDBdX7Lbt7wWCkxJry8ep0ebTUA78Ym2JTDnqttqvVM69X3e3BHJug/wddiMlA7YN5tR0eJENPW3qkGYnezwtrWoy5c4KugHJ5FdatQmTGSKnyfIRnhVrV9gVxQNgObg9xXu/I5vwMujwiGr3dSyWDRxa3cv9B5qePEDbFg/pm8mBPjuZGKCTtVEdfM6sUT+F01JPF+W3CtqGB1eOD9p2A5sU1rMWq7GyeJ/jn52FIV+JaCwDxyOgfZzmJTzAyW2q7Y6CyRGcvq3EtEuLY4iibEP/E25jHJQAvN53q3cwKoYmK5757vNmkv/vfBpKiKoExwvPZTQ3YvbTYZpdq3zbTMfmRuz/8x+8c4wjjhPBzIjVeDuZ9g7Hp8nJTNeRlb1t4zpHXjt9VOI1JvIfYNOYcE60O5VJHvP2sQP0ShfPW/iXm8ew35VJgbZ+xb0bHkeDFUvVorMMphN/hZarFSiXK6X9gj8jYsqcmXJXPbDQmDV0pmF9cKVS0x/fWfhJ7ygp3Klar15e0y/+F7b2NJM/nFKqE8/IJRvj+VepjwbbOj+zijyrdEAmVWJWtTYkhxCJ8WyOUxTOEDxNV8Nin31z/OkMR7FYSe3ZvcDeYGlJzgzrIQgrgiYd19p9PiX3hvZh08ywNOdcRxfZGZdrHOYC6hRjzOkUfxsQQpjTyNZRRTnLBTzv6ZwiMVz4/TTuf/A4Z9womavh8PAwCWwpTVoqKzC0wvF8FjVa19WLAGrAqW7TVjuutUbyYqB7dh96lU0AyzdvV61yjrT81OKVLKIB0dFR9upkmZF8fyo2EARv9YDKux1FbLcEwq1VDUBEk2MwmcFQVxEdh5gbJqE7BT6lq+UPIbwNOV4LFJIV42lBMppZ0SnAY+LijrAlIDN/AE7Qd7Jkh0sGLiIJ1nxONNEJON8BHuSw22A71mKkoo0kETMVQAjco6+iXhAeZrsLCtPJh9cfWbTAG/ybFxPYM7iVbkqIgbROB9iHWJoUB6wg0pDm4zU0Gjfjwwk13zSvzNA==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-secrets
      namespace: monitoring

