---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: goldpinger
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: goldpinger
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: goldpinger
    version: 2.0.2
  values:
    image:
      repository: shanedabes/goldpinger
      tag: 3.0.0.3
    service:
      type: ClusterIP
    ingress:
      enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
  valuesFrom:
  - secretKeyRef:
      name: goldpinger-secrets
      namespace: monitoring
      key: values.yml
