---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: helm-operator
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io
    name: helm-operator
    version: 1.2.0
  values:
    git:
      pollInterval:
        "10m"
      ssh:
        secretName: flux-git-deploy
    image:
      repository: raspbernetes/helm-operator
      tag: v1.2.0
    helm:
      versions: v3
    chartSyncInterval: "15m"
    statusUpdateInternal: "5m"
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
        namespace: flux
        interval: 30s
        scrapeTimeout: 10s
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 4000Mi
